
root: true

env:
  node: true


parser: '@typescript-eslint/parser'

plugins:
  - 'import'
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended'
  - '@antfu'

settings:
  'import/resolver':
    typescript: true
    node: true
rules:
  '@typescript-eslint/consistent-type-imports': "off"
  'no-console': 'warn'
  'import/no-unresolved': 'warn'
  'import/namespace': 'warn'
  'import/default': 'warn'
  'import/export': 'warn'
  'import/named': 'warn'
  'import/order':
    - 'warn'
    - 'groups':
        - 'builtin'
        - 'external'
        - 'object'
        - 'parent'
        - 'internal'
        - 'sibling'
        - 'index'
        - 'type'
      'pathGroups':
        - 'pattern': '@/**'
          'group': 'internal'
          'position': 'after'
        - 'pattern': '~/**'
          'group': 'internal'
          'position': 'after'
      'distinctGroup': true
      'newlines-between': 'always'
